kind: pipeline
type: docker
name: default

steps:
- name: install
  image: node:lts-alpine3.15
  commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: ssh_host
    username: 
      from_secret: ssh_username
    key: 
      from_secret: ssh_key
    port: 
      from_secret: ssh_port
  script:
    - echo "hello"
- name: scp
  image: appleboy/drone-scp
  settings:
    host:
      - 3.134.227.207
    username:
      - root
    key: 
      - from_secret: SSH_PASSWORD
  target:
    - /data/drone/tttita.test
  source:
    - index.html
