kind: pipeline
type: docker
name: default

steps:
- name: install
  image: node:lts-alpine3.15
  commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile

- name: testing
  image: node:lts-alpine3.15
  commands:
    - yarn run test
- name: testing2
  image: node:lts-alpine3.15
  commands:
    - yarn run lint
