kind: pipeline
type: docker
name: default

steps:
- name: install
  image: node:lts-alpine3.15
  commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile
- name: scp
  image: appleboy/drone-scp
  host: ec2-3-134-227-207.us-east-2.compute.amazonaws.com
  username: centos
  secrets: [ ssh_password ]
  target: /data/drone/tttita.test
  source:
    - index.html
